#!/usr/bin/env node
/**
 * Generate a Freemius SANDBOX checkout link for QA testing.
 *
 *   cd api && node scripts/sandbox-link.mjs starter
 *   cd api && node scripts/sandbox-link.mjs growth annual
 *   cd api && node scripts/sandbox-link.mjs business monthly
 *
 * Why this exists:
 *   The "Get Checkout → Sandbox Link" generated by the Freemius dashboard
 *   doesn't include the `licenses` and `currency` params our store
 *   requires, so the bare link errors with "Invalid pricing". This
 *   script uses the SDK's Checkout builder to produce a fully-formed
 *   sandbox URL with sandbox token + ctx + plan + licenses + currency
 *   + billing cycle.
 *
 * Reads from api/.env (or env vars):
 *   FREEMIUS_PRODUCT_ID, FREEMIUS_PUBLIC_KEY, FREEMIUS_SECRET_KEY, FREEMIUS_API_KEY
 *   DATABASE_URL (used to look up plan_id by code)
 *
 * Output: a single sandbox checkout URL printed to stdout.
 */

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";
import { Freemius } from "@freemius/sdk";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const apiRoot = path.resolve(__dirname, "..");

function loadEnv(file) {
    try {
        for (const raw of readFileSync(file, "utf8").split(/\r?\n/)) {
            const line = raw.trim();
            if (!line || line.startsWith("#")) continue;
            const eq = line.indexOf("=");
            if (eq < 0) continue;
            const k = line.slice(0, eq).trim();
            let v = line.slice(eq + 1).trim();
            if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1);
            if (!(k in process.env)) process.env[k] = v;
        }
    } catch { /* env from shell */ }
}
loadEnv(path.join(apiRoot, ".env"));

const requireEnv = ["FREEMIUS_PRODUCT_ID", "FREEMIUS_PUBLIC_KEY", "FREEMIUS_SECRET_KEY", "FREEMIUS_API_KEY", "DATABASE_URL"];
for (const k of requireEnv) {
    if (!process.env[k]) {
        console.error(`Missing env: ${k}`);
        process.exit(1);
    }
}

// ─── CLI args ───────────────────────────────────────────────────────
const planCode = (process.argv[2] || "starter").toLowerCase();
const billingCycle = (process.argv[3] || "monthly").toLowerCase();
if (!["free", "starter", "growth", "business", "unlimited"].includes(planCode)) {
    console.error(`Plan must be one of: free, starter, growth, business, unlimited (got "${planCode}")`);
    process.exit(1);
}
if (!["monthly", "annual", "lifetime"].includes(billingCycle)) {
    console.error(`Billing must be one of: monthly, annual, lifetime (got "${billingCycle}")`);
    process.exit(1);
}

// ─── Resolve freemius_plan_id from DB ───────────────────────────────
const pool = new pg.Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: { rejectUnauthorized: false },
});

let freemiusPlanId;
try {
    const { rows } = await pool.query(
        `SELECT freemius_plan_id, name FROM plans WHERE code = $1 LIMIT 1`,
        [planCode],
    );
    if (rows.length === 0) {
        console.error(`Plan "${planCode}" not found in DB.`);
        process.exit(1);
    }
    if (!rows[0].freemius_plan_id) {
        console.error(`Plan "${planCode}" has no freemius_plan_id (free plan? not yet wired in Freemius?).`);
        process.exit(1);
    }
    freemiusPlanId = String(rows[0].freemius_plan_id);
    console.log(`→ Plan: ${rows[0].name} (code=${planCode}, freemius_plan_id=${freemiusPlanId})`);
} finally {
    await pool.end();
}

// ─── Build sandbox checkout link ────────────────────────────────────
const fs = new Freemius({
    productId: process.env.FREEMIUS_PRODUCT_ID,
    publicKey: process.env.FREEMIUS_PUBLIC_KEY,
    secretKey: process.env.FREEMIUS_SECRET_KEY,
    apiKey: process.env.FREEMIUS_API_KEY,
});

console.log("→ Requesting sandbox token from Freemius API…");
const sandboxParams = await fs.checkout.getSandboxParams();

console.log("→ Building checkout URL with sandbox + plan + licenses=1 + currency=eur…");
const checkout = (await fs.checkout.create())
    .setPlan(freemiusPlanId)
    .setQuota(1)
    .setBillingCycle(billingCycle === "lifetime" ? "lifetime" : billingCycle, "list")
    .setCurrency("eur", "eur", true)
    .setSandbox(sandboxParams);

const url = checkout.getLink();

console.log("\n─".repeat(40));
console.log("✓ SANDBOX CHECKOUT URL:\n");
console.log(url);
console.log("\n─".repeat(40));
console.log("\nTest cards:");
console.log("  Visa OK         4242 4242 4242 4242");
console.log("  Mastercard OK   5555 5555 5555 4444");
console.log("  Refused         4000 0000 0000 0002");
console.log("  CVC: any 3 digits · Exp: any future date · Name/Email: anything");
console.log("\nAfter checkout completes, watch:");
console.log("  · https://tempaloo.com/admin/webhooks  (license.created arrives)");
console.log("  · Your inbox                            (trial-started or payment-received)");
console.log("  · https://tempaloo.com/admin/licenses   (license appears with right status)");
